### PR TITLE
Add blank.mp4 to dist files

### PR DESCRIPTION
**Pull request by silverwind**
### Link to related issue (if applicable) 

https://github.com/Selz/plyr/pull/504

### Sumary of proposed changes 

For a complete "offline" experience, it's necessary to self-host the file, so include it in the dist files for that purpose.

### CODE REVIEW

**Comment by silverwind** [comment]
A cleaner approach could to include the file in the form of a data-uri, in which case, the `blankUrl` option can be dropped, and `plyr.js` would gain 2395 bytes. Shall I go for it?

**Comment by SamPotts** [comment]
I had that before - there was a reason I reverted to the remote file. I can't remember why...

**Comment by silverwind** [comment]
Okay, then let's keep it like this. I'm fine with it.

**Comment by SamPotts** [comment]
Merged to `develop` so will go with `v3.0.0` when it's done 👍

**Pull request merged**
