### PR TITLE
Improvement/loop color area

### PR DESCRIPTION
**Pull request by pchrysa**
### Link to related issue (if applicable) 

#115 

### Sumary of proposed changes 

Display a coloured strip indicating the looped area.

### Image

screen shot 2017-02-15 at 17 15 42

### Task list

- [x] Gulp build completed

### CODE REVIEW

**Comment by SamPotts** [comment]
I'd probably want to do this as markers on the progress bar somehow. I'll look into the styling aspect of it as that kinda looks broken to me.

**Comment by pauliusuza** [comment]
why not having both as options

**Comment by SamPotts** [comment]
Sorry but that just looks like a UI glitch. You could replicate the UI abnormality version using CSS by editing the stylesheet yourself I think. People use Plyr because it looks nice and works well from the feedback I've received. I strive to keep it that way...

**Comment by SamPotts** [comment]
Cheers for this - I'll fix up the UI and add the styling to the CSS

**Pull request merged**
