### PR TITLE
Add blankUrl option to set the URL for blank.mp4

### PR DESCRIPTION
**Pull request by ShimShamSam**
Some of my projects are behind VPNs with strict firewalls. I need to be able to self-host the blank.mp4 file used to cancel network requests. This allows you to specify the URL that is set.

### CODE REVIEW

**Comment by SamPotts** [comment]
Can you make sure you run gulp to generate the compressed files as per the contributing docs?

**Comment by ShimShamSam** [comment]
I couldn't find the contributing docs :( I'll run gulp now

**Comment by ShimShamSam** [comment]
Done

**Comment by ShimShamSam** [comment]
Any word on this?

**Comment by SamPotts** [comment]
This is in the latest version 👍

**Pull request merged**
