### PR TITLE
Updated SASS support

### PR DESCRIPTION
**Pull request by brunowego**
Fixed issues with SASS and updated the code.

### CODE REVIEW

**Comment by SamPotts** [comment]
Is this just the formatting changed to 2 spaces? I usually use tabs or 4 spaces but I noticed GitHub isn't so great at retaining the formatting. I'll merge this shortly.

**Comment by brunowego** [comment]
I made the correction of some problems as well.

**Comment by SamPotts** [comment]
Oh what were they? It was building and working fine for me using the gulp script?

**Comment by SamPotts** [comment]
Ah, I can see an @ reference for a variable that you've fixed. Cool.

**Comment by brunowego** [comment]
You change mixin name (seek-*) and have a error with L119.

**Comment by SamPotts** [comment]
Thanks for that Bruno :+1:

**Pull request merged**
